apiVersion: v1
kind: ConfigMap
metadata:
  name: kuenz-adv-daba-26-config
  namespace: kuenz-adv-daba-26
data:
  TZ: "Europe/Zurich"
  JSON_URL: "http://vmrum.isc.heia-fr.ch/files/DBLP-Citation-network-V18.jsonl"
  MAX_NODES: "10000000"
  NEO4J_IP: "kuenz-adv-daba-26-neo4j-service"
  BATCH_SIZE: "5000"
  LOG_INTERVAL: "500000"
  LOG_LEVEL: "INFO"