apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuenz-adv-daba-26-neo4j-pvc
  namespace: kuenz-adv-daba-26
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi